ld-sharedlib := ikovalacode
ikovalacode-sources := iko-valacode-writer.vala
ikovalacode-vala-sharedlibs := \
	$(top-builddir)/iko/iko \
	$(top-builddir)/ikoast/ikoast \
	$(top-builddir)/ikocas/ikocas

include $(dir $(lastword $(MAKEFILE_LIST)))../make/build.mk
