#!/bin/sh
G_SLICE=always-malloc G_DEBUG=gc-friendly libtool --mode=execute valgrind \
	--tool=massif --depth=5 --alloc-fn=g_malloc --alloc-fn=g_realloc \
	--alloc-fn=g_try_malloc --alloc-fn=g_malloc0 \
	--alloc-fn=g_mem_chunk_alloc -q $*
